// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type LoginDto = {
    /**
     * Matched case-insensitively — the service lowercases before lookup.
     */
    email: string;
    password: string;
    /**
     * True keeps the session past browser close; false/omitted makes it a session cookie.
     */
    remember: boolean;
};

export type UserDto = {
    email: string;
    name: string;
    /**
     * File id of the user's avatar, or null. The frontend builds the image URL
     * from it; the bare id keeps the server ignorant of the frontend proxy path.
     */
    avatarFileId: string | null;
    id: string;
    createdAt: string;
    updatedAt: string;
};

export type FileDto = {
    originalName: string;
    mimeType: string;
    sizeBytes: number;
    id: string;
    createdAt: string;
    updatedAt: string;
};

export type CreateProjectDto = {
    /**
     * Human handle for the project, e.g. `CLT-DevSpec`. Globally unique.
     */
    code: string;
    /**
     * Display name.
     */
    name: string;
    /**
     * Customer or business unit the project belongs to.
     */
    customerBu: string;
    /**
     * Business domain, free text — e.g. `Logistics`.
     */
    domain: string;
    /**
     * What the project is trying to achieve. Long prose, optional.
     */
    objective?: string;
    /**
     * Start date as `YYYY-MM-DD`.
     */
    startsOn?: string;
    /**
     * End date as `YYYY-MM-DD`. Must be on or after `startsOn`.
     */
    endsOn?: string;
};

export type ProjectDto = {
    code: string;
    name: string;
    customerBu: string;
    domain: string;
    objective: string | null;
    status: 'active' | 'archived';
    /**
     * `'YYYY-MM-DD'`, not a Date — wrapping it would re-introduce a timezone.
     */
    startsOn: string | null;
    endsOn: string | null;
    memberCount: number;
    createdByName: string;
    viewerRole: 'owner' | 'member';
    id: string;
    createdAt: string;
    updatedAt: string;
};

export type PaginationDto = {
    page: number;
    limit: number;
};

export type ProjectSortDto = {
    sortBy: 'updatedAt' | 'createdAt' | 'name' | 'code';
    sortOrder: 'ASC' | 'DESC';
};

export type ProjectSummaryDto = {
    code: string;
    name: string;
    customerBu: string;
    domain: string;
    status: 'active' | 'archived';
    memberCount: number;
    /**
     * At most three, owner first. `memberCount - memberNames.length` is the +N chip.
     */
    memberNames: Array<string>;
    viewerRole: 'owner' | 'member';
    id: string;
    createdAt: string;
    updatedAt: string;
};

export type ProjectListDto = {
    items: Array<ProjectSummaryDto>;
    /**
     * Matching rows before paging.
     */
    total: number;
    page: number;
    limit: number;
};

export type UpdateProjectDto = {
    /**
     * Human handle for the project, e.g. `CLT-DevSpec`. Globally unique.
     */
    code?: string;
    /**
     * Display name.
     */
    name?: string;
    /**
     * Customer or business unit the project belongs to.
     */
    customerBu?: string;
    /**
     * Business domain, free text — e.g. `Logistics`.
     */
    domain?: string;
    /**
     * What the project is trying to achieve. Long prose, optional.
     */
    objective?: string;
    /**
     * Start date as `YYYY-MM-DD`.
     */
    startsOn?: string;
    /**
     * End date as `YYYY-MM-DD`. Must be on or after `startsOn`.
     */
    endsOn?: string;
};

export type ProjectMemberDto = {
    userId: string;
    name: string;
    email: string;
    role: 'owner' | 'member';
};

export type AddMemberDto = {
    /**
     * Email of an existing Clarivo account. No invitation is created.
     */
    email: string;
};

export type UpdateProfileDto = {
    name: string;
};

export type ChangePasswordDto = {
    currentPassword: string;
    newPassword: string;
};

export type SourceDto = {
    id: string;
    sourceType: 'doc' | 'web';
    title: string;
    url: string | null;
    status: string;
    failureReason: string | null;
    processedAt: string | null;
};

export type ResearchRequestDto = {
    companyName?: string;
    url?: string;
    /**
     * Optional hint about what they are building, to sharpen the search.
     */
    building?: string;
};

export type ResearchPageViewDto = {
    title: string;
    url: string;
    extract: string;
};

export type ResearchDraftDto = {
    findings_md: string;
    pages: Array<ResearchPageViewDto>;
};

export type ResearchPageDto = {
    title: string;
    url: string;
    extract: string;
};

export type AcceptResearchDto = {
    pages: Array<ResearchPageDto>;
};

export type CoverageDto = {
    covered: number;
    total: number;
};

export type ContextDto = {
    summaryMd: string;
    edited: boolean;
    generatedAt: string | null;
    /**
     * True while a Process-all run is in flight (the frontend polls on it).
     */
    processing: boolean;
    coverage: CoverageDto;
    sources: Array<SourceDto>;
};

export type UpdateSummaryDto = {
    /**
     * The full markdown summary. May be empty to clear it.
     */
    summaryMd: string;
};

export type RegenerateDto = {
    /**
     * Overwrite a human-edited summary. Omitted/false respects the edit.
     */
    force?: boolean;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    200: UserDto;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
    200: unknown;
};

export type AuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerMeResponses = {
    200: UserDto;
};

export type AuthControllerMeResponse = AuthControllerMeResponses[keyof AuthControllerMeResponses];

export type FilesControllerUploadData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/files';
};

export type FilesControllerUploadResponses = {
    201: FileDto;
};

export type FilesControllerUploadResponse = FilesControllerUploadResponses[keyof FilesControllerUploadResponses];

export type FilesControllerDownloadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/files/{id}';
};

export type FilesControllerDownloadResponses = {
    200: unknown;
};

export type ProjectsControllerListData = {
    body?: never;
    path?: never;
    query: {
        pagination: PaginationDto;
        sort: ProjectSortDto;
        /**
         * Case-insensitive substring match against `code` or `name`.
         */
        q?: string;
        status: 'active' | 'archived' | 'all';
    };
    url: '/projects';
};

export type ProjectsControllerListResponses = {
    200: ProjectListDto;
};

export type ProjectsControllerListResponse = ProjectsControllerListResponses[keyof ProjectsControllerListResponses];

export type ProjectsControllerCreateData = {
    body: CreateProjectDto;
    path?: never;
    query?: never;
    url: '/projects';
};

export type ProjectsControllerCreateResponses = {
    201: ProjectDto;
};

export type ProjectsControllerCreateResponse = ProjectsControllerCreateResponses[keyof ProjectsControllerCreateResponses];

export type ProjectsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}';
};

export type ProjectsControllerFindOneResponses = {
    200: ProjectDto;
};

export type ProjectsControllerFindOneResponse = ProjectsControllerFindOneResponses[keyof ProjectsControllerFindOneResponses];

export type ProjectsControllerUpdateData = {
    body: UpdateProjectDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}';
};

export type ProjectsControllerUpdateResponses = {
    200: ProjectDto;
};

export type ProjectsControllerUpdateResponse = ProjectsControllerUpdateResponses[keyof ProjectsControllerUpdateResponses];

export type ProjectsControllerArchiveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/archive';
};

export type ProjectsControllerArchiveResponses = {
    201: ProjectDto;
};

export type ProjectsControllerArchiveResponse = ProjectsControllerArchiveResponses[keyof ProjectsControllerArchiveResponses];

export type ProjectsControllerRestoreData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/restore';
};

export type ProjectsControllerRestoreResponses = {
    201: ProjectDto;
};

export type ProjectsControllerRestoreResponse = ProjectsControllerRestoreResponses[keyof ProjectsControllerRestoreResponses];

export type ProjectsControllerListMembersData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/members';
};

export type ProjectsControllerListMembersResponses = {
    200: Array<ProjectMemberDto>;
};

export type ProjectsControllerListMembersResponse = ProjectsControllerListMembersResponses[keyof ProjectsControllerListMembersResponses];

export type ProjectsControllerAddMemberData = {
    body: AddMemberDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/members';
};

export type ProjectsControllerAddMemberResponses = {
    201: ProjectMemberDto;
};

export type ProjectsControllerAddMemberResponse = ProjectsControllerAddMemberResponses[keyof ProjectsControllerAddMemberResponses];

export type ProjectsControllerRemoveMemberData = {
    body?: never;
    path: {
        id: string;
        userId: string;
    };
    query?: never;
    url: '/projects/{id}/members/{userId}';
};

export type ProjectsControllerRemoveMemberResponses = {
    204: void;
};

export type ProjectsControllerRemoveMemberResponse = ProjectsControllerRemoveMemberResponses[keyof ProjectsControllerRemoveMemberResponses];

export type ProfileControllerUpdateProfileData = {
    body: UpdateProfileDto;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type ProfileControllerUpdateProfileResponses = {
    200: UserDto;
};

export type ProfileControllerUpdateProfileResponse = ProfileControllerUpdateProfileResponses[keyof ProfileControllerUpdateProfileResponses];

export type ProfileControllerChangePasswordData = {
    body: ChangePasswordDto;
    path?: never;
    query?: never;
    url: '/users/me/password';
};

export type ProfileControllerChangePasswordResponses = {
    200: unknown;
};

export type ProfileControllerUploadAvatarData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/users/me/avatar';
};

export type ProfileControllerUploadAvatarResponses = {
    200: UserDto;
};

export type ProfileControllerUploadAvatarResponse = ProfileControllerUploadAvatarResponses[keyof ProfileControllerUploadAvatarResponses];

export type ContextControllerListSourcesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/documents';
};

export type ContextControllerListSourcesResponses = {
    200: Array<SourceDto>;
};

export type ContextControllerListSourcesResponse = ContextControllerListSourcesResponses[keyof ContextControllerListSourcesResponses];

export type ContextControllerUploadData = {
    body: {
        file: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/documents';
};

export type ContextControllerUploadResponses = {
    201: SourceDto;
};

export type ContextControllerUploadResponse = ContextControllerUploadResponses[keyof ContextControllerUploadResponses];

export type ContextControllerResearchData = {
    body: ResearchRequestDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/research';
};

export type ContextControllerResearchResponses = {
    200: ResearchDraftDto;
};

export type ContextControllerResearchResponse = ContextControllerResearchResponses[keyof ContextControllerResearchResponses];

export type ContextControllerAcceptResearchData = {
    body: AcceptResearchDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/research/accept';
};

export type ContextControllerAcceptResearchResponses = {
    201: Array<SourceDto>;
};

export type ContextControllerAcceptResearchResponse = ContextControllerAcceptResearchResponses[keyof ContextControllerAcceptResearchResponses];

export type ContextControllerProcessData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/context/process';
};

export type ContextControllerProcessResponses = {
    201: unknown;
};

export type ContextControllerGetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/context';
};

export type ContextControllerGetResponses = {
    200: ContextDto;
};

export type ContextControllerGetResponse = ContextControllerGetResponses[keyof ContextControllerGetResponses];

export type ContextControllerEditSummaryData = {
    body: UpdateSummaryDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/context/summary';
};

export type ContextControllerEditSummaryResponses = {
    200: ContextDto;
};

export type ContextControllerEditSummaryResponse = ContextControllerEditSummaryResponses[keyof ContextControllerEditSummaryResponses];

export type ContextControllerRegenerateData = {
    body: RegenerateDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/context/regenerate';
};

export type ContextControllerRegenerateResponses = {
    201: ContextDto;
};

export type ContextControllerRegenerateResponse = ContextControllerRegenerateResponses[keyof ContextControllerRegenerateResponses];
