// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type LoginDto = {
    /**
     * Matched case-insensitively — the service lowercases before lookup.
     */
    email: string;
    password: string;
    /**
     * True keeps the session past browser close; false/omitted makes it a session cookie.
     */
    remember: boolean;
};

export type UserDto = {
    email: string;
    name: string;
    /**
     * File id of the user's avatar, or null. The frontend builds the image URL
     * from it; the bare id keeps the server ignorant of the frontend proxy path.
     */
    avatarFileId: string | null;
    id: string;
    createdAt: string;
    updatedAt: string;
};

export type FileDto = {
    originalName: string;
    mimeType: string;
    sizeBytes: number;
    id: string;
    createdAt: string;
    updatedAt: string;
};

export type CreateProjectDto = {
    /**
     * Human handle for the project, e.g. `CLT-DevSpec`. Globally unique.
     */
    code: string;
    /**
     * Display name.
     */
    name: string;
    /**
     * Customer or business unit the project belongs to.
     */
    customerBu: string;
    /**
     * Business domain, free text — e.g. `Logistics`.
     */
    domain: string;
    /**
     * What the project is trying to achieve. Long prose, optional.
     */
    objective?: string;
    /**
     * Start date as `YYYY-MM-DD`.
     */
    startsOn?: string;
    /**
     * End date as `YYYY-MM-DD`. Must be on or after `startsOn`.
     */
    endsOn?: string;
};

export type ProjectDto = {
    code: string;
    name: string;
    customerBu: string;
    domain: string;
    objective: string | null;
    status: 'active' | 'archived';
    /**
     * `'YYYY-MM-DD'`, not a Date — wrapping it would re-introduce a timezone.
     */
    startsOn: string | null;
    endsOn: string | null;
    memberCount: number;
    createdByName: string;
    viewerRole: 'owner' | 'member';
    id: string;
    createdAt: string;
    updatedAt: string;
};

export type PaginationDto = {
    page: number;
    limit: number;
};

export type ProjectSortDto = {
    sortBy: 'updatedAt' | 'createdAt' | 'name' | 'code';
    sortOrder: 'ASC' | 'DESC';
};

export type ProjectSummaryDto = {
    code: string;
    name: string;
    customerBu: string;
    domain: string;
    status: 'active' | 'archived';
    memberCount: number;
    /**
     * At most three, owner first. `memberCount - memberNames.length` is the +N chip.
     */
    memberNames: Array<string>;
    viewerRole: 'owner' | 'member';
    id: string;
    createdAt: string;
    updatedAt: string;
};

export type ProjectListDto = {
    items: Array<ProjectSummaryDto>;
    /**
     * Matching rows before paging.
     */
    total: number;
    page: number;
    limit: number;
};

export type UpdateProjectDto = {
    /**
     * Human handle for the project, e.g. `CLT-DevSpec`. Globally unique.
     */
    code?: string;
    /**
     * Display name.
     */
    name?: string;
    /**
     * Customer or business unit the project belongs to.
     */
    customerBu?: string;
    /**
     * Business domain, free text — e.g. `Logistics`.
     */
    domain?: string;
    /**
     * What the project is trying to achieve. Long prose, optional.
     */
    objective?: string;
    /**
     * Start date as `YYYY-MM-DD`.
     */
    startsOn?: string;
    /**
     * End date as `YYYY-MM-DD`. Must be on or after `startsOn`.
     */
    endsOn?: string;
};

export type ProjectMemberDto = {
    userId: string;
    name: string;
    email: string;
    role: 'owner' | 'member';
};

export type AddMemberDto = {
    /**
     * Email of an existing Clarivo account. No invitation is created.
     */
    email: string;
};

export type ProjectDocumentDto = {
    title: string;
    originalName: string;
    mimeType: string;
    sizeBytes: number;
    /**
     * The file id, so a citation chip can link straight at GET /files/:id.
     */
    fileId: string;
    status: 'archived' | 'pending' | 'parsing' | 'summarizing' | 'proposing' | 'ready' | 'failed';
    error: string | null;
    /**
     * Accepted blocks sourced from this document.
     */
    blockCount: number;
    id: string;
    createdAt: string;
    updatedAt: string;
};

export type RenameDocumentDto = {
    title: string;
};

export type KnowledgeRefDto = {
    id: string;
    documentId: string;
    title: string;
    /**
     * So a chip can link straight at GET /files/:id.
     */
    fileId: string;
    locator: string | null;
    quote: string;
};

export type KnowledgeBlockDto = {
    section: 'overview' | 'scope' | 'stakeholders' | 'process' | 'data_model' | 'constraints' | 'integrations' | 'glossary' | 'open_questions';
    position: number;
    statement: string;
    confidence: 'stated' | 'implied' | 'uncertain';
    origin: 'ai' | 'human';
    state: 'proposed' | 'accepted' | 'rejected' | 'superseded';
    kind: 'update' | 'add' | 'conflict';
    supersedesId: string | null;
    sourceDocumentId: string | null;
    /**
     * Set means a human owns this wording; no document can silently replace it.
     */
    editedAt: string | null;
    authorName: string | null;
    refs: Array<KnowledgeRefDto>;
    id: string;
    createdAt: string;
    updatedAt: string;
};

export type KnowledgeSectionDto = {
    section: 'overview' | 'scope' | 'stakeholders' | 'process' | 'data_model' | 'constraints' | 'integrations' | 'glossary' | 'open_questions';
    blocks: Array<KnowledgeBlockDto>;
};

export type KnowledgePageDto = {
    sections: Array<KnowledgeSectionDto>;
    /**
     * Documents that became ready after the current brief was written.
     */
    briefStaleCount: number;
};

export type CitationDto = {
    documentId: string;
    locator?: string | null;
    quote: string;
};

export type CreateBlockDto = {
    section: 'overview' | 'scope' | 'stakeholders' | 'process' | 'data_model' | 'constraints' | 'integrations' | 'glossary' | 'open_questions';
    statement: string;
    confidence: 'stated' | 'implied' | 'uncertain';
    /**
     * A human block needs no citation — the author is the source.
     */
    refs?: Array<CitationDto>;
};

export type UpdateBlockDto = {
    statement?: string;
    confidence?: 'stated' | 'implied' | 'uncertain';
    refs?: Array<CitationDto>;
};

export type ProposalItemDto = {
    section: 'overview' | 'scope' | 'stakeholders' | 'process' | 'data_model' | 'constraints' | 'integrations' | 'glossary' | 'open_questions';
    position: number;
    statement: string;
    confidence: 'stated' | 'implied' | 'uncertain';
    origin: 'ai' | 'human';
    state: 'proposed' | 'accepted' | 'rejected' | 'superseded';
    kind: 'update' | 'add' | 'conflict';
    supersedesId: string | null;
    sourceDocumentId: string | null;
    /**
     * Set means a human owns this wording; no document can silently replace it.
     */
    editedAt: string | null;
    authorName: string | null;
    refs: Array<KnowledgeRefDto>;
    id: string;
    createdAt: string;
    updatedAt: string;
    /**
     * The block this proposal updates or disagrees with, when it has one.
     */
    target: KnowledgeBlockDto | null;
};

export type ProposalGroupDto = {
    documentId: string;
    documentTitle: string;
    proposals: Array<ProposalItemDto>;
};

export type ResolveConflictDto = {
    resolution?: 'keep_existing' | 'use_new' | 'write_own';
    /**
     * Required for write_own: the wording the human wants instead of both.
     */
    statement?: string;
};

export type UpdateProfileDto = {
    name: string;
};

export type ChangePasswordDto = {
    currentPassword: string;
    newPassword: string;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    200: UserDto;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
    200: unknown;
};

export type AuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerMeResponses = {
    200: UserDto;
};

export type AuthControllerMeResponse = AuthControllerMeResponses[keyof AuthControllerMeResponses];

export type FilesControllerUploadData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/files';
};

export type FilesControllerUploadResponses = {
    201: FileDto;
};

export type FilesControllerUploadResponse = FilesControllerUploadResponses[keyof FilesControllerUploadResponses];

export type FilesControllerDownloadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/files/{id}';
};

export type FilesControllerDownloadResponses = {
    200: unknown;
};

export type ProjectsControllerListData = {
    body?: never;
    path?: never;
    query: {
        pagination: PaginationDto;
        sort: ProjectSortDto;
        /**
         * Case-insensitive substring match against `code` or `name`.
         */
        q?: string;
        status: 'active' | 'archived' | 'all';
    };
    url: '/projects';
};

export type ProjectsControllerListResponses = {
    200: ProjectListDto;
};

export type ProjectsControllerListResponse = ProjectsControllerListResponses[keyof ProjectsControllerListResponses];

export type ProjectsControllerCreateData = {
    body: CreateProjectDto;
    path?: never;
    query?: never;
    url: '/projects';
};

export type ProjectsControllerCreateResponses = {
    201: ProjectDto;
};

export type ProjectsControllerCreateResponse = ProjectsControllerCreateResponses[keyof ProjectsControllerCreateResponses];

export type ProjectsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}';
};

export type ProjectsControllerFindOneResponses = {
    200: ProjectDto;
};

export type ProjectsControllerFindOneResponse = ProjectsControllerFindOneResponses[keyof ProjectsControllerFindOneResponses];

export type ProjectsControllerUpdateData = {
    body: UpdateProjectDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}';
};

export type ProjectsControllerUpdateResponses = {
    200: ProjectDto;
};

export type ProjectsControllerUpdateResponse = ProjectsControllerUpdateResponses[keyof ProjectsControllerUpdateResponses];

export type ProjectsControllerArchiveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/archive';
};

export type ProjectsControllerArchiveResponses = {
    201: ProjectDto;
};

export type ProjectsControllerArchiveResponse = ProjectsControllerArchiveResponses[keyof ProjectsControllerArchiveResponses];

export type ProjectsControllerRestoreData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/restore';
};

export type ProjectsControllerRestoreResponses = {
    201: ProjectDto;
};

export type ProjectsControllerRestoreResponse = ProjectsControllerRestoreResponses[keyof ProjectsControllerRestoreResponses];

export type ProjectsControllerListMembersData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/members';
};

export type ProjectsControllerListMembersResponses = {
    200: Array<ProjectMemberDto>;
};

export type ProjectsControllerListMembersResponse = ProjectsControllerListMembersResponses[keyof ProjectsControllerListMembersResponses];

export type ProjectsControllerAddMemberData = {
    body: AddMemberDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/members';
};

export type ProjectsControllerAddMemberResponses = {
    201: ProjectMemberDto;
};

export type ProjectsControllerAddMemberResponse = ProjectsControllerAddMemberResponses[keyof ProjectsControllerAddMemberResponses];

export type ProjectsControllerRemoveMemberData = {
    body?: never;
    path: {
        id: string;
        userId: string;
    };
    query?: never;
    url: '/projects/{id}/members/{userId}';
};

export type ProjectsControllerRemoveMemberResponses = {
    204: void;
};

export type ProjectsControllerRemoveMemberResponse = ProjectsControllerRemoveMemberResponses[keyof ProjectsControllerRemoveMemberResponses];

export type ContextControllerListDocumentsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/projects/{projectId}/documents';
};

export type ContextControllerListDocumentsResponses = {
    200: Array<ProjectDocumentDto>;
};

export type ContextControllerListDocumentsResponse = ContextControllerListDocumentsResponses[keyof ContextControllerListDocumentsResponses];

export type ContextControllerUploadData = {
    body: {
        file: Blob | File;
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/projects/{projectId}/documents';
};

export type ContextControllerUploadResponses = {
    201: ProjectDocumentDto;
};

export type ContextControllerUploadResponse = ContextControllerUploadResponses[keyof ContextControllerUploadResponses];

export type ContextControllerRenameData = {
    body: RenameDocumentDto;
    path: {
        projectId: string;
        documentId: string;
    };
    query?: never;
    url: '/projects/{projectId}/documents/{documentId}';
};

export type ContextControllerRenameResponses = {
    200: ProjectDocumentDto;
};

export type ContextControllerRenameResponse = ContextControllerRenameResponses[keyof ContextControllerRenameResponses];

export type ContextControllerRereadData = {
    body?: never;
    path: {
        projectId: string;
        documentId: string;
    };
    query?: never;
    url: '/projects/{projectId}/documents/{documentId}/reread';
};

export type ContextControllerRereadResponses = {
    201: ProjectDocumentDto;
};

export type ContextControllerRereadResponse = ContextControllerRereadResponses[keyof ContextControllerRereadResponses];

export type ContextControllerArchiveData = {
    body?: never;
    path: {
        projectId: string;
        documentId: string;
    };
    query?: never;
    url: '/projects/{projectId}/documents/{documentId}/archive';
};

export type ContextControllerArchiveResponses = {
    201: ProjectDocumentDto;
};

export type ContextControllerArchiveResponse = ContextControllerArchiveResponses[keyof ContextControllerArchiveResponses];

export type KnowledgeControllerRegenerateBriefData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/projects/{projectId}/knowledge/brief/regenerate';
};

export type KnowledgeControllerRegenerateBriefResponses = {
    201: unknown;
};

export type KnowledgeControllerGetPageData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/projects/{projectId}/knowledge';
};

export type KnowledgeControllerGetPageResponses = {
    200: KnowledgePageDto;
};

export type KnowledgeControllerGetPageResponse = KnowledgeControllerGetPageResponses[keyof KnowledgeControllerGetPageResponses];

export type KnowledgeControllerCreateBlockData = {
    body: CreateBlockDto;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/projects/{projectId}/knowledge/blocks';
};

export type KnowledgeControllerCreateBlockResponses = {
    201: KnowledgeBlockDto;
};

export type KnowledgeControllerCreateBlockResponse = KnowledgeControllerCreateBlockResponses[keyof KnowledgeControllerCreateBlockResponses];

export type KnowledgeControllerDeleteBlockData = {
    body?: never;
    path: {
        projectId: string;
        blockId: string;
    };
    query?: never;
    url: '/projects/{projectId}/knowledge/blocks/{blockId}';
};

export type KnowledgeControllerDeleteBlockResponses = {
    204: void;
};

export type KnowledgeControllerDeleteBlockResponse = KnowledgeControllerDeleteBlockResponses[keyof KnowledgeControllerDeleteBlockResponses];

export type KnowledgeControllerUpdateBlockData = {
    body: UpdateBlockDto;
    path: {
        projectId: string;
        blockId: string;
    };
    query?: never;
    url: '/projects/{projectId}/knowledge/blocks/{blockId}';
};

export type KnowledgeControllerUpdateBlockResponses = {
    200: KnowledgeBlockDto;
};

export type KnowledgeControllerUpdateBlockResponse = KnowledgeControllerUpdateBlockResponses[keyof KnowledgeControllerUpdateBlockResponses];

export type KnowledgeControllerListProposalsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/projects/{projectId}/knowledge/proposals';
};

export type KnowledgeControllerListProposalsResponses = {
    200: Array<ProposalGroupDto>;
};

export type KnowledgeControllerListProposalsResponse = KnowledgeControllerListProposalsResponses[keyof KnowledgeControllerListProposalsResponses];

export type KnowledgeControllerAcceptData = {
    body: ResolveConflictDto;
    path: {
        projectId: string;
        blockId: string;
    };
    query?: never;
    url: '/projects/{projectId}/knowledge/proposals/{blockId}/accept';
};

export type KnowledgeControllerAcceptResponses = {
    201: unknown;
};

export type KnowledgeControllerRejectData = {
    body?: never;
    path: {
        projectId: string;
        blockId: string;
    };
    query?: never;
    url: '/projects/{projectId}/knowledge/proposals/{blockId}/reject';
};

export type KnowledgeControllerRejectResponses = {
    201: unknown;
};

export type ProfileControllerUpdateProfileData = {
    body: UpdateProfileDto;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type ProfileControllerUpdateProfileResponses = {
    200: UserDto;
};

export type ProfileControllerUpdateProfileResponse = ProfileControllerUpdateProfileResponses[keyof ProfileControllerUpdateProfileResponses];

export type ProfileControllerChangePasswordData = {
    body: ChangePasswordDto;
    path?: never;
    query?: never;
    url: '/users/me/password';
};

export type ProfileControllerChangePasswordResponses = {
    200: unknown;
};

export type ProfileControllerUploadAvatarData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/users/me/avatar';
};

export type ProfileControllerUploadAvatarResponses = {
    200: UserDto;
};

export type ProfileControllerUploadAvatarResponse = ProfileControllerUploadAvatarResponses[keyof ProfileControllerUploadAvatarResponses];
