// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type LoginDto = {
    /**
     * Matched case-insensitively — the service lowercases before lookup.
     */
    email: string;
    password: string;
    /**
     * True keeps the session past browser close; false/omitted makes it a session cookie.
     */
    remember: boolean;
};

export type UserDto = {
    email: string;
    name: string;
    id: string;
    createdAt: string;
    updatedAt: string;
};

export type FileDto = {
    originalName: string;
    mimeType: string;
    sizeBytes: number;
    id: string;
    createdAt: string;
    updatedAt: string;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    200: UserDto;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
    200: unknown;
};

export type AuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerMeResponses = {
    200: UserDto;
};

export type AuthControllerMeResponse = AuthControllerMeResponses[keyof AuthControllerMeResponses];

export type FilesControllerUploadData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/files';
};

export type FilesControllerUploadResponses = {
    201: FileDto;
};

export type FilesControllerUploadResponse = FilesControllerUploadResponses[keyof FilesControllerUploadResponses];

export type FilesControllerDownloadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/files/{id}';
};

export type FilesControllerDownloadResponses = {
    200: unknown;
};
